# # GET  http://localhost:8000/api/activate/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MX0.sU30l9m_tmqh_HzL9lvvy7nv7g-9Q18sxtRwMMslpQA
# # Content-Type: application/json
# # {}

GET  http://127.0.0.1:8000/api/user_info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NzEwOTA3LCJpYXQiOjE3MzQ3MTA2MDcsImp0aSI6ImQ2MmU4MGRiNDk4NzRhYWQ5ZGY2MGE4YjY5NzczZTBkIiwidXNlcl9pZCI6MX0.MEQx9K3zqd08-6Jpd25LAgEg5R0_RFNScnx4ILkvVx8

{

}

#######

PUT  http://127.0.0.1:8000/api/update_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NzEwOTA3LCJpYXQiOjE3MzQ3MTA2MDcsImp0aSI6ImQ2MmU4MGRiNDk4NzRhYWQ5ZGY2MGE4YjY5NzczZTBkIiwidXNlcl9pZCI6MX0.MEQx9K3zqd08-6Jpd25LAgEg5R0_RFNScnx4ILkvVx8

{
  # "email":"mio@gmail.com",
  "first_name":"89s"
}

##############
##############

POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
  "email": "tests@example.com",
  "password": "orllld123"
}

##############
##############

GET http://127.0.0.1:8000/api/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwMjAxMjk5LCJpYXQiOjE3MzAyMDA5OTksImp0aSI6ImU3ZjNkOTk3OWE1YTRmMWFiYzBmZmE3MmRiZDIzYTYwIiwidXNlcl9pZCI6MX0.BgwFvzLKLvOHTcBCvezXLMFUx5SChD2yJQp__ccOYzc

{
	"chat_id": 4
}

##############
##############


POST  http://127.0.0.1:8000/api/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "orllld123"
}





##############
##############


POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{
  "username": "uassxjsaa",
  "email": "test@example.com",
  "password": "orllld123"
}

##############
##############

POST   http://127.0.0.1:8000/api/friend_req
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0ODkwMzg2LCJpYXQiOjE3MzQ4OTAwODYsImp0aSI6ImE5Nzg4YWVjZGUzMDQ2YmNiNWMwM2QxZGIwOGVkNWI1IiwidXNlcl9pZCI6Mn0.gRmtFaJrhzZMC1cw3_y5qm_vGWdxJONV8KpgmzcDuR8

{
  "username":"uassxjaa"
}

##################
##################

PUT  http://127.0.0.1:8000/api/friend_req
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0ODkwNDA5LCJpYXQiOjE3MzQ4OTAxMDksImp0aSI6IjFmN2E1ODczMWY5ODQwYjc5Y2JkNjcwNmNkNTI5NWFlIiwidXNlcl9pZCI6MX0.bQ4ClJFtbgLUzgZSeO6NKDecLAYyVSV6mrs_MQBmRZI

{
  "type":"res",
  "username":"uassxjsaa"
}