# # GET  http://localhost:8000/api/activate/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MX0.sU30l9m_tmqh_HzL9lvvy7nv7g-9Q18sxtRwMMslpQA
# # Content-Type: application/json
# # {}

GET  http://127.0.0.1:8000/api/user_info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NzEwOTA3LCJpYXQiOjE3MzQ3MTA2MDcsImp0aSI6ImQ2MmU4MGRiNDk4NzRhYWQ5ZGY2MGE4YjY5NzczZTBkIiwidXNlcl9pZCI6MX0.MEQx9K3zqd08-6Jpd25LAgEg5R0_RFNScnx4ILkvVx8

{

}

#######

PUT  http://127.0.0.1:8000/api/update_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NzEwOTA3LCJpYXQiOjE3MzQ3MTA2MDcsImp0aSI6ImQ2MmU4MGRiNDk4NzRhYWQ5ZGY2MGE4YjY5NzczZTBkIiwidXNlcl9pZCI6MX0.MEQx9K3zqd08-6Jpd25LAgEg5R0_RFNScnx4ILkvVx8

{
  # "email":"mio@gmail.com",
  "first_name":"89s"
}

##############
##############

POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Set-Cookie: refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNTY5ODk1MCwiaWF0IjoxNzM1MDk0MTUwLCJqdGkiOiJhM2I2N2UyMzkyYjQ0NTMyODk0MDdjZTNiMWI5OGMyNCIsInVzZXJfaWQiOjN9.R4rsCbh8f3cQ1JUjsRz5iii0hH1HNl2dhyN-dfKRyVo; HttpOnly; Path=/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MDk0NDUwLCJpYXQiOjE3MzUwOTQxNTAsImp0aSI6ImZhMDAyYjExNGNlYzRjNGM5NzI5MzQ1NDY3NTI4NWQ3IiwidXNlcl9pZCI6M30.7xLz1coPw1t8qqiDdn3904Sa-Hvvcu9YT0r7bgn1sI0

{
  "email": "test@example.com",
  "password": "orllld123"
}

##############
##############

GET http://127.0.0.1:8000/api/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMwMjAxMjk5LCJpYXQiOjE3MzAyMDA5OTksImp0aSI6ImU3ZjNkOTk3OWE1YTRmMWFiYzBmZmE3MmRiZDIzYTYwIiwidXNlcl9pZCI6MX0.BgwFvzLKLvOHTcBCvezXLMFUx5SChD2yJQp__ccOYzc

{
	"chat_id": 4
}

##############
##############

POST  http://127.0.0.1:8000/api/login
Content-Type: application/json

{
  "email": "testaa@example.com",
  "password": "orllld123"
}



##############
##############

POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{
  "username": "testaa",
  "email": "testaa@example.com",
  "password": "orllld123"
}

##############
##############

GET http://127.0.0.1:8000/api/friend_req/?type=received&page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MDk0MDg2LCJpYXQiOjE3MzUwOTM3ODYsImp0aSI6ImFmMThhNTJjZjBhYjQ3MWU4NWRiZDE2NDNlYjEwMGUyIiwidXNlcl9pZCI6M30.KGobf7SYuYNGzFEvXAaQP6QZajOU9U5EW5PSqkiYhiw

{
  "username":"testaa"
}
##################
##################

POST http://127.0.0.1:8000/api/oauth
Content-Type: application/json

{
  "platform":"42"

}