# Generated by Django 4.2.16 on 2024-12-15 19:18

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpeg', upload_to='avatars/', validators=[profiles.models.validate_image]),
        ),
    ]
