# Generated by Django 4.2.16 on 2024-12-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='game',
            field=models.CharField(max_length=16),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
