# Generated by Django 4.2.16 on 2025-01-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_player1_alter_game_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='loser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
